baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "The Herald of Nobility"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/chatgpt-image-8-giu-2025-17_41_03.png"]